export const SEARCHTERM_CHANGE = "SEARCHTERM_CHANGE";

export const REQUEST_TRACKS_PENDING = 'REQUEST_TRACKS_PENDING';
export const REQUEST_TRACKS_SUCCESS = 'REQUEST_TRACKS_SUCCESS';
export const REQUEST_TRACKS_FAILED = 'REQUEST_TRACKS_FAILED';
export const UPDATE_SEARCHRESULTS = 'UPDATE_SEARCHRESULTS';
