export const REQUEST_TRACKS_PENDING = 'REQUEST_TRACKS_PENDING';
export const REQUEST_TRACKS_SUCCESS = 'REQUEST_TRACKS_SUCCESS';
export const REQUEST_TRACKS_FAILED = 'REQUEST_TRACKS_FAILED';
export const UPDATE_SEARCHRESULTS = 'UPDATE_SEARCHRESULTS';

export const UPDATE_PLAYLIST_TRACKS = 'UPDATE_PLAYLIST_TRACKS';

export const UPDATE_PLAYLIST_NAME = 'UPDATE_PLAYLIST_NAME';
